server/src/main/java/com/octopus/teamcity/opentelemetry/server/TeamCityBuildListener.java
Some logging in the plugin needed updated to improve readability. 
Logs sent as errors should have been sent as warns or info logs. These have been updated. 
Other logs have added full stops on the end.
=> Update logging in plugin

common/src/main/java/com/octopus/teamcity/opentelemetry/common/PluginConstants.java
@cailyoung noticed in the honeycomb spans the attribute for artifacts_size was truncated with artifactName + ".teamcity.opentelemetry_artifact_size". This proved difficult for searching by all artifacts in a build in honeycomb. 
Artifact size attribute now truncated as artifactName + "_artifact_size". This is subject to change in the future.
=> Fix artifact name attribute in spans

common/src/main/java/com/octopus/teamcity/opentelemetry/common/PluginConstants.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/TeamCityBuildListener.java
In honeycomb traces, some build events where experiencing multiple build start events. Deduced this was probably due to identifying spans by buildTypeID which might not be unique in TeamCity for each build. 
Now build spans will be identified by buildID. 
Hopefully we'll not see multiple build start events per build.
=> Update build span identifier by buildID instead of buildTypeID

server/src/main/java/com/octopus/teamcity/opentelemetry/server/OTELHelper.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/TeamCityBuildListener.java
BlockMessages are used in the plugin to retrieve individual build steps under a build. There was no parent child relationship previously between the blockMessages, where all blockMessages were treated as a child of the build span.
This pull request creates parent child relationships between these blockMessages. I
If the blockMessage has a parent message, create a child span referencing that parent blockMessage span.
If the blockMessage does not have a parent message, create a child span that will be referencing the build as the parent span.
Before, all build Steps and blockMessages were a child of the build and flattened. 
After this change, all Build Steps will be nested with reference to a parent message if required.
Sanity check my understanding of the blockMessage hierarchy.
=> Adding parent child relationships to blockMessages

common/src/main/java/com/octopus/teamcity/opentelemetry/common/PluginConstants.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/TeamCityBuildListener.java
To improve usability of honeycomb queries, a request was made to add all attributes from a build span to their subsequent build step spans. 
An additional attribute of `octopus.teamcity.opentelemetry.build_checkout_time_ms` has been calculated and added to only the top level build spans.
1. A method `setCommonSpanBuildAttributes` now sets the build attributes for all build spans, and build step spans, which includes the queue message and block message types. 
2. Build checkout time is calculated in method `calculateBuildCheckoutTime` from the block message that contains "checkout" in its text. The checkout time is the difference between the timestamp of the msg and the finish time of the message. This is then added to a new concurrent hashmap of the trace id. The attribute for checkout …
=> Build Step Attribute Additions

gradle/versions.gradle
Due to Log4Shell vulnerability 
Upgrading the log4j package version in gradle wrapper to patched version.
=> upgrade log4j gradle wrapper version to mitigate Log4Shell vulnerability

.github/dependabot.yml
We want to make sure we're updating dependencies to avoid bit rot and vulnerabilities caused by out of date dependency issues.
This PR adds the dependabot config to keep our gradle config up to date.
* eyes should be fine.
=> Create a dependabot config

README.md, server/src/main/java/com/octopus/teamcity/opentelemetry/server/BuildStorageManagerImpl.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/ProjectConfigurationSettingsController.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/TeamCityBuildListener.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/helpers/HelperPerBuildOTELHelperFactory.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/helpers/OTELHelperImpl.java
Rather than the server log
We were in a bit of an icky spot with logging - we were logging to the main server log file, rather than our own specific log file, meaning it was hard to find our logs, but also we were polluting the main server log with too much info.
We now log to our own file. 
Instructions are provided as to how setup TeamCity logging.
* eyes should be fine
* does the readme change make sense?
=> Log to our own plugin specific file

server/src/main/resources/buildServerResources/buildOverviewHoneycombExtension.jsp, server/src/main/resources/buildServerResources/buildOverviewZipkinExtension.jsp
Previously, when builds had problems, the link and the build problems were jammed together - it didn't look pretty.
We now stick a bucket load (that's a technical term right there) of spacing underneath it:
* eyeballs will be fine
=> Add padding under the link so that build problems show nicely

server/src/main/java/com/octopus/teamcity/opentelemetry/server/TeamCityBuildListener.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/helpers/HelperPerBuildOTELHelperFactory.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/helpers/NullOTELHelperImpl.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/helpers/OTELHelper.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/helpers/OTELHelperImpl.java, server/src/test/java/com/octopus/teamcity/opentelemetry/server/TeamCityBuildListenerTest.java
We had a bit of an issue where we weren't releasing objects, so we need up with 25,000 threads in use, along with a growing number of 5XX errors being returned, slow performance, and excessive memory utilisation.
Fixes https://github.com/OctopusDeploy/opentelemetry-teamcity-plugin/issues/29
We now remove the `OTELHelper` from the lookup dictionary when we've finished with it.
I've tested this locally, and seen that it removes it from the dictionary at the end of the build as expected.
A local test would be nice, but not mandatory.
=> Cleanup the otelHelper after we've finished

server/src/main/java/com/octopus/teamcity/opentelemetry/server/ProjectConfigurationTab.java
A bug was reported that when trying to use NewRelic as a `custom` service, it crashes with
```
java.lang.reflect.InvocationTargetException: null
at jdk.internal.reflect.GeneratedMethodAccessor194.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
at jetbrains.buildServer.web.impl.PagePlaceImpl$ProxyHandler.invokeExtensionMethodUnsafe(PagePlaceImpl.java:21) ~[web.jar:?]
at jetbrains.buildServer.web.impl.PagePlaceImpl$ProxyHandler.invoke(PagePlaceImpl.java:4) ~[web.jar:?]
at com.sun.proxy.$Proxy93.fillModel(Unknown Source) ~[?:?]
at jetbrains.buildServer.web.impl.PageExtensionsInterceptor.fillModel(PageExtensionsInterceptor.java:85) ~[web.jar:?]
at …
```
=> Don't try and unscramble an empty value

server/src/main/java/com/octopus/teamcity/opentelemetry/server/TeamCityBuildListener.java
[SC-45521]
As originally implemented, `service_name` for build spans gets set to be the build configuration 'external ID' (the human-readable PascalCase slug TeamCity generates for build configurations).
This prevents easy identification of these spans in trace analysis tools in aggregate as there's nothing in common across all of them - no 'type' property, if you like.
This PR changes these spans to have a constant value, so that in trace analysis tooling we can select _all_ builds and analyse them in aggregate.
As this changes the data shape of the spans, we intend to bump a minor version when merging this change.
Note - if you are relying on the current contents of this parameter in your tooling, it is still available at `octopus.teamcity.opentelemetry.build_type_external_id`
(a build …
=> Change build span service_name to be the same for all builds

common/src/main/java/com/octopus/teamcity/opentelemetry/common/PluginConstants.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/TeamCityBuildListener.java
As part of the SLI/SLO work this quarter in the Rock Solid Builds Team, we want to include Test Executions in the metrics we measure and report on and ultimately include as part of our indicators and objectives.
For now, this PR does not remove the existing `$TEST_BLOCK$` spans being sent, so there will be an increase in spans per build. We are still iterating on how to best show these tests in the waterfall and wanted to leave the existing spans as they are for now.
This PR updates the OopenTelemetry (OTEL) Plugin for TeamCity to include test execution spans.
=> Update OTEL plugin to include Test Execution Spans

server/src/main/java/com/octopus/teamcity/opentelemetry/server/TeamCityBuildListener.java
#167 made a choice to ship the entire test output on failure, however in some of our test suites that output is _large_.
Eventually we will want to do this, however we'd like to put a flag around that feature so that we can safely test it in production.
For now, we are reverting this particular attribute.
=> Don't ship the entire test output on failure

server/src/main/java/com/octopus/teamcity/opentelemetry/server/TeamCityBuildListener.java
After #167 and #169 I noticed that we don't have build number or branch on the test events, which are critical to our intended use of them in our analysis tooling.
This PR adds build attributes to the test spans, so that we can filter out tests by branch or group by version, etc.
=> Propagate build attributes to test spans

README.md
in #195, I upgraded to java 17, but I missed the readme.
Updates the readme to fix java11 to java17
=> Update the readme to mention java17

server/src/main/java/com/octopus/teamcity/opentelemetry/server/ProjectConfigurationTab.java, server/src/main/resources/buildServerResources/projectConfigurationSettings.jsp
In https://github.com/OctopusDeploy/reportportal-teamcity-plugin/pull/58 (which has very similar bones to this plugin), we fixed the display of the overridden project / inherited project.
This PR implements the same fix here.
=> Fix display of inheritance/overridden project

server/src/main/java/com/octopus/teamcity/opentelemetry/server/ProjectConfigurationSettingsController.java, server/src/main/resources/buildServerResources/projectConfigurationSettings.js, server/src/main/resources/buildServerResources/projectConfigurationSettings.jsp
The code has always been in here to show a status message on save, but I never managed to get it working.
I decided to tackle it today.
We now:
* show a message after save
* reload after a successful save
These changes inspired by the [teamcity-priority](https://github.com/JetBrains/teamcity-priority-queue) queue plugin (especially [createPriorityClass.jsp](https://github.com/JetBrains/teamcity-priority-queue/blob/master/server/resources/buildServerResources/createPriorityClass.jsp) and [priorityClass.js](https://github.com/JetBrains/teamcity-priority-queue/blob/1de4153e022c13b1128a7cd632a8c656c67aac6d/server/resources/buildServerResources/js/priorityClass.js)).
=> Provide UI updates on save

server/src/main/java/com/octopus/teamcity/opentelemetry/server/ProjectConfigurationSettingsController.java
When settings are changed, we dont log an audit reason, which means that we cant see what changed in git history.
Similar to https://github.com/OctopusDeploy/reportportal-teamcity-plugin/pull/109, this adds the audit reason when settings change.
=> Add details to the "what changed" when changing settings

common/src/main/java/com/octopus/teamcity/opentelemetry/common/PluginConstants.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/TeamCityBuildListener.java
We want to be able to exclude composite builds in our SLO calcs, as the start time is the start of _any_ dependency, not it's immediate dependencies.
We are now emitting two new properties:
* `octopus.teamcity.opentelemetry.build_is_composite`
* `octopus.teamcity.opentelemetry.build_id`
The second one is a bit of a drive by bonus - i would have assumed it was already there.
=> Add build_id and is_composite flag

server/src/main/java/com/octopus/teamcity/opentelemetry/server/TeamCityBuildListener.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/helpers/NullOTELHelperImpl.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/helpers/OTELHelper.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/helpers/OTELHelperImpl.java, server/src/test/java/com/octopus/teamcity/opentelemetry/server/OTELHelperTest.java, server/src/test/java/com/octopus/teamcity/opentelemetry/server/TeamCityBuildListenerTest.java
While working on some other stuff, we found that `getParentSpan` wasn't clearly named.
This renames it to `getOrCreateParentSpan` to better reflect what it actually does.
=> Refactor method for clarity

server/src/main/java/com/octopus/teamcity/opentelemetry/server/TeamCityBuildListener.java
In a big build graph, where there are many builds depending on other builds, we found that the spans were not linked correctly - all child spans were linked to the root, not to the immediate parent.
We now link a child span to the "most distant" direct dependancy.
ie, if you've got:
```
-> test 1 \
/           \
Calc Version -> test 2  -> Gate Test -> Full Chain
\    \           /            /
\    -> test 3 /            /
\                         /
------------------------
```
Then:
* `test1`, `test2` and `test3` will be a child of `Gate Test`
* `Calc Version` will be a child of `Full Chain` (even though it could be linked to any one of `test1`, `test2` or `test3`)
* `Gate Test` will be a child of `Full Chain`
=> Link parent spans better

server/src/main/java/com/octopus/teamcity/opentelemetry/server/TeamCityBuildListener.java
Similar to https://github.com/OctopusDeploy/teamcity-reportportal-plugin/pull/265, adding structured logging.
This adds thread context, so we know which build we're referring to across all log messages.
This will require a change to the teamcity log4net config, to add a `%X`:
from
```
<PatternLayout pattern="[%d] %6p - %30.30c - %m%n" charset="UTF-8"/>
```
to
```
<PatternLayout pattern="[%d] %6p - %30.30c - %X - %m%n" charset="UTF-8"/>
```
=> Add build and root build to context, so it ends up on log messages

server/src/main/java/com/octopus/teamcity/opentelemetry/server/TeamCityBuildListener.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/helpers/HelperPerBuildOTELHelperFactory.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/helpers/NullOTELHelperImpl.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/helpers/OTELHelper.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/helpers/OTELHelperImpl.java, server/src/test/java/com/octopus/teamcity/opentelemetry/server/OTELHelperTest.java, server/src/test/java/com/octopus/teamcity/opentelemetry/server/TeamCityBuildListenerTest.java
We're stills seeing missing spans. It's confusing why.
This adds some logging around the `release` at the end of the cleanup, so we can see if it's getting cleaned up too early.
It also tidies up a bunch of other logging that was making my :eye_twitch: while I was log searching.
=> Improve logging, especially around cleanup

server/src/main/java/com/octopus/teamcity/opentelemetry/server/TeamCityBuildListener.java
While investigating logs, i spotted:
```
[2024-09-13 01:50:49,249]  ERROR - y.server.TeamCityBuildListener - {teamcity.build.id=14082131, teamcity.root.build.id=14082074} - Exception in Build Finish caused by: java.lang.NullPointerException: Cannot invoke "io.opentelemetry.context.ImplicitContextKeyed.storeInContext(io.opentelemetry.context.Context)" because "value" is nullnull, with message: Cannot invoke "io.opentelemetry.context.ImplicitContextKeyed.storeInContext(io.opentelemetry.context.Context)" because "value" is null, and stacktrace: [io.opentelemetry.context.Context.with(Context.java:174), com.octopus.teamcity.opentelemetry.server.helpers.OTELHelperImpl.createTransientSpan(OTELHelperImpl.java:68), com.octopus.teamcity.opentelemetry.server.TeamCityBuildListener.createBlockMessageSp …
```
=> Fix bug where it was attempting to use a null parent span

settings.gradle
The repo used to be `opentelemetry-teamcity-plugin`, but my mind always thought of "teamcity" first, so I've renamed it to be `teamcity-opentelemetry-plugin` to make more sense.
This PR renames the gradle rootproject to match.
=> Fix project name

.github/pull-request-template.md, .octopus/deployment_process.ocl
After the repo was renamed, I missed a few spots where the old repo was mentioned.
Renames to the new name
=> Fixes after repo-rename

common/src/main/java/com/octopus/teamcity/opentelemetry/common/PluginConstants.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/endpoints/custom/CustomOTELEndpointHandler.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/endpoints/honeycomb/HoneycombOTELEndpointHandler.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/endpoints/zipkin/ZipKinOTELEndpointHandler.java
The metrics shipped with #339 helped to prove that we were dropping spans.
[sc-96078]
This bumps up the batch size and queue size, which will allow large traces to be shipped without dropping spans.
In future, we may want to make these configurable via env var/system property, but for now, I'm hardcoding.
Dropped spans (the green line):
No more dropped spans (the green line):
=> Increase throughput of the BatchSpanProcessor

server/build.gradle, server/src/main/java/com/octopus/teamcity/opentelemetry/server/endpoints/honeycomb/HoneycombOTELEndpointHandler.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/helpers/OTELHelperImpl.java
I've been seeing deprecation warnings for a while.
This updates the dependencies to their non-deprecated versions.
=> Updates to fix deprecation warnings

server/src/main/java/com/octopus/teamcity/opentelemetry/server/endpoints/OTELEndpointFactory.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/endpoints/honeycomb/HoneycombOTELEndpointHandler.java
Including the teamcity node name in the metrics will help us isolate primary/secondary (and hopefully preprod/prod, but I'm not sure about that).
Passes through the `NodesService` so we can log `teamcity.node.id`.
On my local (single node) setup, it logs it as `MAIN_SERVER`.
=> Include teamcity node name in metrics

server/src/main/java/com/octopus/teamcity/opentelemetry/server/endpoints/IOTELEndpointHandler.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/endpoints/custom/CustomOTELEndpointHandler.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/endpoints/honeycomb/HoneycombOTELEndpointHandler.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/endpoints/zipkin/ZipKinOTELEndpointHandler.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/helpers/HelperPerBuildOTELHelperFactory.java
It's useful to know at the metrics level, which builds are related.
Adds `teamcity.build_promotion.id` (which maps 1:1 with buildId) to the metrics emitted.
=> Log build id with metrics

server/src/main/java/com/octopus/teamcity/opentelemetry/server/endpoints/OTELEndpointFactory.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/endpoints/zipkin/ZipkinOTELEndpointHandler.java
I happened to see Zipkin capitalised as `ZipKin`.
This PR fixes that.
=> Fix capitalisation of zipkin

server/src/main/java/com/octopus/teamcity/opentelemetry/server/BuildOverviewExtensionController.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/BuildStorageManagerImpl.java
I noticed a few (super low priority) issues with these logs:
* it's not including the build id as an attribute
* it should be `for`, not `or`.
=> Slight logging tweaks

server/src/main/java/com/octopus/teamcity/opentelemetry/server/endpoints/IOTELEndpointHandler.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/endpoints/custom/CustomOTELEndpointHandler.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/endpoints/honeycomb/HoneycombOTELEndpointHandler.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/endpoints/zipkin/ZipKinOTELEndpointHandler.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/helpers/HelperPerBuildOTELHelperFactory.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/helpers/OTELHelperImpl.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/helpers/OTELMetrics.java, server/src/test/java/com/octopus/teamcity/opentelemetry/server/OTELHelperTest.java, server/src/test/java/com/octopus/teamcity/opentelemetry/server/TeamCityBuildListenerTest.java
I had success all during testing for the metrics shipping, but as soon as I merged and used the prod one, it stopped working.
Interestingly, it started working after teamcity was restarted due to cluster upgrade. This suggests to me that the global was getting into a bad state due to concurrency.
This is wise anyway, as we want to avoid the use of the global properties, as it allows metrics per project. 
[sc-96078]
We now:
* no longer set the GlobalOpenTelemetry config
* ~add an attribute to the metric, so we can see what build it relates to~ this was done in https://github.com/OctopusDeploy/teamcity-opentelemetry-plugin/pull/348.
* shutdown the metric reader, so that it doesn't leak threads
=> Dont use globals for the tc metrics settings

server/src/main/java/com/octopus/teamcity/opentelemetry/server/ProjectConfigurationSettingsController.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/TeamCityBuildListener.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/helpers/HelperPerBuildOTELHelperFactory.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/helpers/OTELHelperFactory.java, server/src/test/java/com/octopus/teamcity/opentelemetry/server/TeamCityBuildListenerTest.java
We were caching the `OTELHelper` by the build, as we weren't sure whether the settings would change between builds, so we wanted to lookup the settings at the start of each build.
However, this means we're creating a whole lot more OTEL things than we really need to, on the off chance it changes.
Turns out all we needed to do was remove the item from the cache when the project was updated, and we automatically get the updates.
So, now, we cache based on project, and create far fewer `BatchSpanProcessor_WorkerThread`, hopefully fixing #368.
:thinking: If an update happens while a build is running, half of the traces could go to the old settings, and new ones go to the new place, but that is probably okay. Probably.
=> Cache OTEL helper by project rather than build

server/src/main/java/com/octopus/teamcity/opentelemetry/server/helpers/HelperPerProjectOTELHelperFactory.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/helpers/NullOTELHelperImpl.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/helpers/OTELHelper.java, server/src/main/java/com/octopus/teamcity/opentelemetry/server/helpers/OTELHelperImpl.java, server/src/main/resources/META-INF/build-server-plugin-Octopus.TeamCity.Opentelemetry.xml
We're still seeing thread leaks. See #368.
This PR adds adds the ability to evict OTELHelper entries from the cache.
By default, it checks every 5 mins, and evicts unused entries after 1 hour.
These values can be overridden by setting `teamcity.otel.helper.cleanup.timer.delay.ms` and `teamcity.otel.helper.cache.duration.ms` in the teamcity internal properties (Administration -> Diagnostics -> Internal Properties.
=> Evict entries from the cache to release threads

teamcity-plugin.xml
A simple fix, changing the vendor url from the old https://octopusdeploy.com to https://octopus.com
=> Fix the vendor url
